[package]
name = "weather-util"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dotenv = "0.15.0"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
tokio = { version = "1.38.0", features = ["full"] }
